### ISSUE TITLE
Issue: configure_logging error due to structlog dependency

### ISSUE THREAD

**Issue by giuliop** [algorandfoundation/puya#61]
puya depends on the structlog package.
puya works well with structlog 23.2.0 but breaks with the latest version 23.3.0.

If structlog 23.3.0 is used, you get the following error message trying to compile:
`AttributeError: 'PuyaConsoleRender' object has no attribute '_level_to_color'`

For now pinning structlog to 23.2.0 is needed to make Puya work.

**Comment by daniel-makerx** [comment]
Hi @giuliop, thanks for this report. We have [fixed](https://github.com/algorandfoundation/puya/pull/54) this issue in the main branch, and the fix will be available in the next release

**Comment by daniel-makerx** [comment]
You should be able to update Puya to 0.3.0 now to resolve this
